// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmbjgkaatimsntzpsbqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtYmpna2FhdGltc250enBzYnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTIyMDksImV4cCI6MjA3MjcyODIwOX0.8r0Bm1qft68QA2XJCsaa8zA1gZ-WLdo_dNoserqk_YU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});