// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Read from Vite env (or process.env fallback)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (process.env as any).VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || (process.env as any).VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn('[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY');
}

declare global {
  var __supabase_client__: ReturnType<typeof createClient> | undefined;
}

export const supabase =
  (globalThis as any).__supabase_client__ ??= createClient(SUPABASE_URL!, SUPABASE_ANON_KEY!);